[build]
  base = "apps/robin-noguier"
  command = "cd ../.. && ./dev_setup.sh && pnpm build --filter=robin-noguier"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"