name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  # Skip Git hooks in CI environment
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.12.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set deployment environment variables
        run: |
          # Automatically detect custom domain for ryleebrasseur/portfolio
          if [ "${{ github.repository }}" = "ryleebrasseur/portfolio" ]; then
            echo "CUSTOM_DOMAIN=ryleeworks.com" >> $GITHUB_ENV
            echo "VITE_BASE_PATH=/" >> $GITHUB_ENV
            echo "Auto-detected repository: ryleebrasseur/portfolio"
            echo "Using custom domain: ryleeworks.com"
            echo "Setting base path to root (/)"
          elif [ -n "${{ vars.CUSTOM_DOMAIN }}" ]; then
            echo "CUSTOM_DOMAIN=${{ vars.CUSTOM_DOMAIN }}" >> $GITHUB_ENV
            echo "VITE_BASE_PATH=/" >> $GITHUB_ENV
            echo "Using configured custom domain: ${{ vars.CUSTOM_DOMAIN }}"
            echo "Setting base path to root (/)"
          else
            echo "CUSTOM_DOMAIN=" >> $GITHUB_ENV
            echo "VITE_BASE_PATH=/portfolio/" >> $GITHUB_ENV
            echo "Using GitHub Pages subdirectory"
            echo "Setting base path to /portfolio/"
          fi

      - name: Build
        run: pnpm build --filter=robin-noguier
        env:
          NODE_ENV: production

      - name: Create CNAME file for custom domain
        if: env.CUSTOM_DOMAIN != ''
        run: |
          echo "${{ env.CUSTOM_DOMAIN }}" > ./apps/robin-noguier/dist/CNAME
          echo "Created CNAME file with domain: ${{ env.CUSTOM_DOMAIN }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/robin-noguier/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4